package com.momtime.shared.data

import com.momtime.shared.domain.EventType
import com.momtime.shared.domain.OccurrenceState
import com.momtime.shared.engine.Reconcile
import kotlin.time.Duration
import kotlin.time.Duration.Companion.hours
import kotlin.time.Instant

/**
 * The `Reconcile` command over the repositories (ADR 0030, invariant 3). Dispatching it is how the watchdog,
 * the foreground and boot all learn that an occurrence has become `MISSED`: none of them changes an
 * occurrence's state, they call this and the domain decides. It is idempotent. An occurrence that already has
 * a terminal event, or whose grace has not expired, is left exactly as it is, and a second dispatch finds
 * nothing to do.
 *
 * Each `MISSED` event is written together with its state change in one transaction
 * ([OccurrenceRepository.transition]), and carries `effectiveAt`, the grace expiry, so when this runs does
 * not change what adherence reports.
 */
class ReconcileCommand(
    private val occurrences: OccurrenceRepository,
    private val templates: ScheduleTemplateRepository,
    private val events: EventRepository,
    private val newId: () -> String,
) {
    /** Derives `MISSED` for every open occurrence whose grace has expired as of [now]. Returns how many. */
    fun dispatch(now: Instant): Int {
        var missed = 0
        for (occurrence in occurrences.findOpen()) {
            // An occurrence whose template is gone has no criticality, so it has no grace to expire.
            val template = templates.findById(occurrence.templateId) ?: continue
            val hasTerminalEvent = events.findForOccurrence(occurrence.id).any { it.eventType in TERMINAL_EVENTS }
            val event = Reconcile.evaluate(occurrence, template.criticality, now, hasTerminalEvent, newId) ?: continue
            occurrences.transition(occurrence.id, OccurrenceState.MISSED, event)
            missed++
        }
        return missed
    }

    private companion object {
        val TERMINAL_EVENTS =
            setOf(
                EventType.COMPLETED,
                EventType.COMPLETED_BACKFILLED,
                EventType.SKIPPED,
                EventType.MISSED,
                // A withdrawal closes an occurrence as the other four do (ADR 0079): it can never become MISSED.
                EventType.WITHDRAWN,
            )
    }
}

/**
 * The rolling window of occurrences (ARCHITECTURE.md section 3.2), regenerated by the daily worker and on any
 * template edit. Materialising one template is one atomic repository operation ([OccurrenceRepository
 * .materialiseWindow], ADR 0036), and that transaction, not how the work is scheduled, is what keeps two
 * overlapping runs from leaving a duplicate or a partial batch. Running it twice over the same window creates
 * nothing the second time (golden scenario 12).
 */
class MaterialiseCommand(
    private val templates: ScheduleTemplateRepository,
    private val occurrences: OccurrenceRepository,
    private val newId: () -> String,
) {
    /** Materialises every active template over [now, now + [WINDOW]). Returns how many occurrences were created. */
    fun dispatch(now: Instant): Int =
        templates
            .findAllActive()
            .sumOf { occurrences.materialiseWindow(it, now, now + WINDOW, newId).size }

    companion object {
        /** How far ahead occurrences are materialised. Not weeks: see ARCHITECTURE.md section 5.3. */
        val WINDOW: Duration = 48.hours
    }
}
