package com.momtime.android.capability

import com.momtime.shared.domain.DeliveryCapability
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The delivery resolution for every combination of its six inputs (ADR 0050). The expected result is
 * data in `delivery-resolution-table.csv`, written and kept up to date by hand. It is never generated or
 * regenerated by code: a script that derives the rows from the rules is a second implementation of those
 * rules, and if it shares a misreading with the code the test cannot fail on it (the precedent is the baseline
 * snapshot that regenerated itself, ADR 0035). A change to a row is a decision, and shows as a diff of that file.
 * Nor is the answer computed here, for the same reason: a test that used the code's own rules would pass
 * whatever the rules were. The test enumerates all 64 combinations and fails if one is missing from the
 * table, or listed twice, or if the table holds a row no combination produces, so an input added to
 * `CapabilityInputs` cannot go unhandled silently.
 */
class DeliveryResolutionTableTest {
    private val every: List<CapabilityInputs> =
        listOf(false, true).flatMap { exact ->
            listOf(false, true).flatMap { fsi ->
                listOf(false, true).flatMap { notifications ->
                    listOf(false, true).flatMap { battery ->
                        listOf(false, true).flatMap { overlay ->
                            listOf(false, true).map { critical ->
                                CapabilityInputs(exact, fsi, notifications, battery, overlay, critical)
                            }
                        }
                    }
                }
            }
        }

    @Test
    fun `there are 64 combinations of the six inputs`() {
        assertEquals(64, every.size)
        assertEquals(64, every.toSet().size)
    }

    @Test
    fun `the table covers every combination exactly once and nothing else`() {
        val rows = DeliveryTable.rows()
        val byInputs = rows.groupBy { it.inputs }

        val missing = every.filter { it !in byInputs }
        assertTrue("combinations missing from the table (${missing.size}): $missing", missing.isEmpty())
        val duplicated = byInputs.filter { it.value.size > 1 }.keys
        assertTrue("combinations listed more than once: $duplicated", duplicated.isEmpty())
        val unknown = byInputs.keys - every.toSet()
        assertTrue("rows no combination produces: $unknown", unknown.isEmpty())
        assertEquals(64, rows.size)
    }

    @Test
    fun `every combination resolves to what the table says`() {
        val wrong =
            DeliveryTable.rows().mapNotNull { row ->
                val actual = resolveDelivery(row.inputs)
                if (actual == row.expected) null else "${row.line}\n    resolved to $actual"
            }
        assertTrue(
            "${wrong.size} of 64 combinations resolve differently from the table:\n${wrong.joinToString("\n")}",
            wrong.isEmpty(),
        )
    }

    @Test
    fun `the table is not vacuous`() {
        val tiers = DeliveryTable.rows().map { it.expected.tier }.toSet()
        assertEquals("the table must exercise every tier", ResolvedTier.entries.toSet(), tiers)
        val rows = DeliveryTable.rows()
        assertTrue(rows.any { it.expected.undeliverable })
        assertTrue(rows.any { it.expected.audioOnly })
        assertTrue(rows.any { it.expected.overlayAvailable })
        assertTrue(rows.any { it.expected.fullScreenIntent && it.expected.headsUp })
        // A blocked Critical channel keeps Tier 3 out even with everything else granted.
        val blocked = rows.first { it.inputs == CapabilityInputs(true, true, true, true, true, false) }
        assertEquals(ResolvedTier.EXACT, blocked.expected.tier)
    }

    @Test
    fun `the android tier maps to the shared capability, one to one`() {
        assertEquals(DeliveryCapability.TIER_3, ResolvedTier.FULL.toDeliveryCapability())
        assertEquals(DeliveryCapability.TIER_2, ResolvedTier.EXACT.toDeliveryCapability())
        assertEquals(DeliveryCapability.TIER_1, ResolvedTier.INEXACT.toDeliveryCapability())
        assertEquals(
            "the mapping must reach every shared tier exactly once",
            DeliveryCapability.entries.toSet(),
            ResolvedTier.entries.map { it.toDeliveryCapability() }.toSet(),
        )
        assertEquals(DeliveryCapability.entries.size, ResolvedTier.entries.size)
    }

    @Test
    fun `the resolution carries the mapped capability`() {
        val full = resolveDelivery(CapabilityInputs(true, true, true, true, true, true))
        assertEquals(DeliveryCapability.TIER_3, full.capability)
        val inexact = resolveDelivery(CapabilityInputs(false, true, true, true, true, true))
        assertEquals(DeliveryCapability.TIER_1, inexact.capability)
        assertEquals(DeliveryMechanism.SET_AND_ALLOW_WHILE_IDLE, inexact.mechanism)
    }
}
